trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_VERSION: '1.6.0'

steps:
- script: |
    sudo apt-get update && sudo apt-get install -y unzip wget
    wget https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
    unzip terraform_1.6.0_linux_amd64.zip
    sudo mv terraform /usr/local/bin/
    terraform -version
  displayName: 'Install Terraform'

- script: |
    terraform init
    terraform validate
    terraform plan
    terraform apply -auto-approve
  displayName: 'Terraform Apply'
  workingDirectory: 'env/KE'
