trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_VERSION: '1.6.0'

steps:
- task: UseTerraform@0
  inputs:
    terraformVersion: $(TF_VERSION)

- script: |
    terraform init
    terraform validate
    terraform plan
    terraform apply -auto-approve
  displayName: 'Terraform Apply'
  workingDirectory: 'env/KE'
