trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_VERSION: '1.6.0'

steps:
- script: |
    sudo apt-get update && sudo apt-get install -y unzip wget
    wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
    unzip terraform_${TF_VERSION}_linux_amd64.zip
    sudo mv terraform /usr/local/bin/
    terraform -version
  displayName: 'Install Terraform'

- script: |
    terraform init
    terraform validate
    terraform plan -out=tfplan
  displayName: 'Terraform Plan'
  workingDirectory: 'env/KE'

- script: |
    terraform apply -auto-approve tfplan
  displayName: 'Terraform Apply'
  workingDirectory: 'env/KE'
