name: Terraform KE

on:
  push:
    paths:
      - "./env/ke/**"
      - ".github/workflows/terraform-ke.yml"

jobs:
  call-template:
    uses: ./.github/workflows/terraform-template.yml
    with:
      env_name: "ke"
      working_directory: "./env/ke"
      var_file: "env/ke/dev.tfvars"
